services:
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    public: true

  #
  # Repositories
  #
  order.repository:
    class: Nastoletni\Orders\Domain\OrderRepository
    factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
    arguments:
        - Nastoletni\Orders\Domain\Order

  item.repository:
    class: Nastoletni\Orders\Domain\ItemRepository
    factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
    arguments:
        - Nastoletni\Orders\Domain\Item

  #
  # Controllers
  #
  order.apiController:
    class: Nastoletni\Orders\UserInterface\Api\OrderController
    tags: ['controller.service_arguments']

  item.apiController:
    class: Nastoletni\Orders\UserInterface\Api\ItemController
    tags: ['controller.service_arguments']

  user.apiController:
    class: Nastoletni\Orders\UserInterface\Api\UserController
    tags: ['controller.service_arguments']
    arguments:
      $encoderFactory: '@security.encoder_factory'

  #
  # Command handlers
  #
  placeOrder.handler:
    class: Nastoletni\Orders\Application\Command\Handler\PlaceOrderHandler

  changeOrderStage.handler:
    class: Nastoletni\Orders\Application\Command\Handler\ChangeOrderStageHandler

  deleteOrder.handler:
    class: Nastoletni\Orders\Application\Command\Handler\DeleteOrderHandler

  #
  # Queries
  #
  allItemsQuery:
    class: Nastoletni\Orders\Application\Query\AllItemsQuery

  allOrdersQuery:
    class: Nastoletni\Orders\Application\Query\AllOrdersQuery

  #
  # Event listeners
  #
  eventListener.jsonRequestBodyListener:
    class: Nastoletni\Orders\Symfony\EventListener\JSONRequestBodyListener
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  #
  # Other stuff
  #
  jwt.provider.configuration:
    class: Nastoletni\Orders\Application\SignedJwtProviderConfiguration
    arguments:
      $signer: '@security.tokenSigner'
      $secret: '%secret%'

  jwt.provider:
    class: Nastoletni\Orders\Application\SignedJwtProvider

  security.tokenSigner:
    class: Lcobucci\JWT\Signer\Hmac\Sha256

  security.apiAuthenticator:
    class: Nastoletni\Orders\Symfony\Security\ApiTokenAuthenticator